version: '3.8'

x-java-ops: &java-ops
  JAVA_TOOL_OPTIONS: -Xss512k -XX:MaxMetaspaceSize=50m -XX:MaxRAMPercentage=70

x-spring-ops: &spring-ops
  SPRING_PROFILES_ACTIVE: gradle, dk
  SPRING_SLEUTH_TRACE-ID128: false
  logging.level.com.mk: DEBUG
  SPRING_ZIPKIN_BASEURL: http://tempo:9411

services:
  eva:
    image: com.mk/eva-exchange-rx:1.0.0
    labels: 
      type: spring
    deploy:
      resources:
          limits:
            cpus: '2'
            memory: 512M
          reservations:
            memory: 128M
    ports: 
      - 9081:8080
    environment:
       <<: *java-ops
       <<: *spring-ops

  sword:
    image: com.mk/swordfish:1.0.0
    labels: 
      type: spring
    deploy:
      resources:
          limits:
            cpus: '4'
            memory: 512M
          reservations:
            memory: 128M
    ports: 
      - 9082:8080
    environment:
       <<: *spring-ops

  sword-rx:
    image: com.mk/swordfish-rx:1.0.0
    labels: 
      type: spring
    deploy:
      replicas: 0
      resources:
          limits:
            cpus: '2'
            memory: 512M
          reservations:
            memory: 128M
    ports: 
      - 9083:8080
    environment:
       <<: *spring-ops
  

  # Todo
  # -[]: Kong API gateway
  # -[]: Keycloak (MS propagation token) 
  # -[]: Dependency tracker with ciclonex https://owasp.org/www-project-dependency-track/ (vulnerabilities, license)
  # -[]: API automaticion API tests https://github.com/apiaryio/dredd
  # -[]: Concourse
  # -[]: Semantic Release