apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
      derivedFields:
        - name: TraceID
          datasourceUid: tempo
          matcherRegex: \[.+,(.+?),
          url: $${__value.raw}
    secureJsonData:
      httpHeaderValue1: "tenant1"
