apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  url: http://prometheus:9090
  jsonData:
    httpMethod: GET
    exemplarTraceIdDestinations:
      - name: TraceID
        datasourceUid: tempo
        urlDisplayLabel: View in Tempo