apiVersion: 1

datasources:
- name: Tempo
  type: tempo
  access: proxy
  url: http://tempo:3200
  uid: tempo
  jsonData:
    httpMethod: GET
    tracesToLogs:
      datasourceUid: 'loki'
      # they must be attached by the instrumentation
      # tags: [ 'pod', 'namespace' ]
      # extend time span a little, to ensure catching all logs of that span
      spanStartTimeShift: 1s
      spandEndTimeShift: 1s
      lokiSearch: true
    serviceMap:
      datasourceUid: 'prometheus'